name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-dev build-essential git zip unzip openjdk-17-jdk clang make pkg-config libjpeg-turbo libpng fftw
        pip install --upgrade pip
        pip install buildozer

    - name: Initialize Buildozer
      run: |
        buildozer init
        # تعديل buildozer.spec تلقائيًا لتضمين المتطلبات الأساسية
        sed -i 's/^requirements =.*/requirements = python3,opencv-python-headless/' buildozer.spec
        sed -i 's/^title =.*/title = MyOpenCVApp/' buildozer.spec
        sed -i 's/^package.name =.*/package.name = myopencvapp/' buildozer.spec
        sed -i 's/^package.domain =.*/package.domain = org.example/' buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyOpenCVApp-APK
        path: bin/*.apk
